/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package login;


import java.util.List;

import javax.swing.JOptionPane;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author AlumnadoTarde
 */
public class Login extends javax.swing.JFrame {

    
    public static notasPrueba App;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CUsuario = new javax.swing.JTextField();
        jlLogin = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        CPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        PRegistrar = new javax.swing.JPanel();
        jlRegistrar = new javax.swing.JLabel();
        PEntrar = new javax.swing.JPanel();
        jlEntrar = new javax.swing.JLabel();
        PFondo = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jlUsuario.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jlUsuario.setText("USUARIO");
        bg.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 330, 10));

        CUsuario.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        CUsuario.setForeground(new java.awt.Color(115, 115, 115));
        CUsuario.setBorder(null);
        bg.add(CUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 330, 30));

        jlLogin.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(51, 51, 51));
        jlLogin.setText("LOG IN");
        bg.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jlPass.setBackground(new java.awt.Color(51, 51, 51));
        jlPass.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jlPass.setForeground(new java.awt.Color(51, 51, 51));
        jlPass.setText("CONTRASEÑA");
        bg.add(jlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        CPass.setForeground(new java.awt.Color(115, 115, 115));
        CPass.setBorder(null);
        bg.add(CPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 330, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 330, 10));

        PRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        PRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        PRegistrar.setToolTipText("");
        PRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jlRegistrar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlRegistrar.setForeground(new java.awt.Color(0, 102, 102));
        jlRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRegistrar.setText("REGISTRAR");
        jlRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jlRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlRegistrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout PRegistrarLayout = new javax.swing.GroupLayout(PRegistrar);
        PRegistrar.setLayout(PRegistrarLayout);
        PRegistrarLayout.setHorizontalGroup(
            PRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        PRegistrarLayout.setVerticalGroup(
            PRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        bg.add(PRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 100, 40));

        PEntrar.setBackground(new java.awt.Color(0, 102, 102));
        PEntrar.setToolTipText("");
        PEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlEntrar.setBackground(new java.awt.Color(0, 153, 153));
        jlEntrar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jlEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEntrar.setText("ENTRAR");
        jlEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEntrarMouseClicked(evt);
            }

        });

        javax.swing.GroupLayout PEntrarLayout = new javax.swing.GroupLayout(PEntrar);
        PEntrar.setLayout(PEntrarLayout);
        PEntrarLayout.setHorizontalGroup(
            PEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        PEntrarLayout.setVerticalGroup(
            PEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(PEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, 40));

        PFondo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PFondoLayout = new javax.swing.GroupLayout(PFondo);
        PFondo.setLayout(PFondoLayout);
        PFondoLayout.setHorizontalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        PFondoLayout.setVerticalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        bg.add(PFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 520));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/italia-desconocida-il-lago-di-resia-800x500-1_1.jpg"))); // NOI18N
        bg.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 660, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>  // </editor-fold>//GEN-END:initComponents

    private void jlRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistrarMouseClicked
         Registro re=new Registro ();
         re.setVisible(true);
    }//GEN-LAST:event_jlRegistrarMouseClicked

    private void jlRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistrarMouseEntered
        
    }//GEN-LAST:event_jlRegistrarMouseEntered

                   
   
    private void jlEntrarMouseClicked(java.awt.event.MouseEvent evt) {                                      
        String email = CUsuario.getText();
        String pass = new String (CPass.getPassword());
        String hashPass = hashPassword(pass);

        if (authUsuario(email, hashPass)) {
            notasPrueba App = new notasPrueba(email);
            App.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            CUsuario.setText("");
            CPass.setText("");
            //CAMBIAR ESTO POR UN JLABEL QUE DIGA QUE EL USUARIO O CONTRASEÑA SON INCORRECTOS
            
        }
    }

    private boolean authUsuario(String email, String hashPass) {
    try {
        List<String> lineas = Files.readAllLines(Paths.get("data/users.txt"));
        for (String linea : lineas) {
            String[] division = linea.split(":");
            if (division.length == 3) {
                //String existeName = division[0];
                String existeEmail = division[1];
                String existeHashPass = division[2];

                if (existeEmail.equals(email) && existeHashPass.equals(hashPass)) {
                    return true;
                }
            }
        }
    } catch (IOException ex) {
        //CAMBIAR ESTO POR UN JLABEL QUE DIGA QUE HUBO UN ERROR
    }

    return false;
    
    }

        private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(password.getBytes());
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
        return null;
    }
}

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPass;
    private javax.swing.JTextField CUsuario;
    private javax.swing.JPanel PEntrar;
    private javax.swing.JPanel PFondo;
    private javax.swing.JPanel PRegistrar;
    private javax.swing.JLabel background;
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlEntrar;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlRegistrar;
    private javax.swing.JLabel jlUsuario;
    // End of variables declaration//GEN-END:variables
}
