/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package login;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author AlumnadoTarde
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlPassError = new javax.swing.JLabel();
        jlNameError = new javax.swing.JLabel();
        jlCorreoError = new javax.swing.JLabel();
        jlGuardarError = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel1.setText("NOMBRE");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(115, 115, 115));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlNameError.setText("");
                jlGuardarError.setText("");
            }
        });

        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 270, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 270, -1));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel2.setText("CORREO ELECTRÓNICO");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(115, 115, 115));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCorreoError.setText("");
                jlGuardarError.setText("");
            }
        });

        bg.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jPasswordField1.setForeground(new java.awt.Color(115, 115, 115));
        jPasswordField1.setBorder(null);
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 270, 30));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPassError.setText("");
                jlGuardarError.setText("");
            }
        });


        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REGISTRARSE");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarCampos();
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarCampos();
            }
        });

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jlPassError.setForeground(new java.awt.Color(255, 0, 0));
        jlPassError.setText("");
 
        bg.add(jlPassError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, 30));

        jlNameError.setForeground(new java.awt.Color(255, 0, 0));
        jlNameError.setText("");
        bg.add(jlNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 86, 200, 30));

        jlCorreoError.setForeground(new java.awt.Color(255, 0, 0));
        jlCorreoError.setText("");
        bg.add(jlCorreoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 200, 30));

        jlGuardarError.setForeground(new java.awt.Color(255, 0, 0));
        jlGuardarError.setText("");
        bg.add(jlGuardarError, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 360, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Registro registro;
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    public static boolean validarEmail (String email) {
		Pattern pattern = Pattern.compile("^([0-9a-zA-Z]+[-._+&])*[0-9a-zA-Z]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}$");
		Matcher matcher = pattern.matcher(email);
		return matcher.matches();
	}
    
    private  void validarCampos(){
        boolean valido = true;
        if(jTextField1.getText().isEmpty()){
            jlNameError.setText("El nombre no puede estar vacío");
            valido = false;
        }else{
            jlNameError.setText("");
        }
        
        if(jTextField2.getText().isEmpty()){
            jlCorreoError.setText("El correo no puede estar vacío");
            valido = false;
        }else if (!validarEmail(jTextField2.getText())){
            jlCorreoError.setText("El correo no es válido");
            valido = false;
            }else{

            jlCorreoError.setText("");
        }
        
        if(jPasswordField1.getPassword().length <8){
            jlPassError.setText("La contraseña debe tener más de 8 caractéres.");
            valido=false;
        }else{
            jlPassError.setText("");
        }

        if (valido){
            String name = jTextField1.getText();
            String email = jTextField2.getText();
            String pass = new String(jPasswordField1.getPassword());
            String hashPass = hashPassword(pass);
            if (usuarioExiste(name, email, hashPass)) {
                jlGuardarError.setForeground(new java.awt.Color(255, 0, 0));
                jlGuardarError.setText("El usuario ya existe. Cambia los datos.");
                jTextField1.setText("");
                jTextField2.setText("");
                jPasswordField1.setText("");
            }else{
            guardarData(name, email, hashPass);
            crearDirectorioUsuario(email);
            jlGuardarError.setForeground(new java.awt.Color(0, 153, 76));
            jlGuardarError.setText("Datos guardados correctamente.");
            jTextField1.setText("");
            jTextField2.setText("");
            jPasswordField1.setText("");
        }
    
    }
}

    private boolean usuarioExiste(String name, String email, String hashPass) {
    File file = new File("data/users.txt");
    if (!file.exists()) {
        return false;
        
    }
    try {
        List<String> lineas = Files.readAllLines(Paths.get("data/users.txt"));
        for (String linea : lineas) {
            String[] division = linea.split(":");
            if (division.length == 3) {
                String existeName = division[0];
                String existeEmail = division[1];

                if (existeName.equals(name) && existeEmail.equals(email)) {
                    return true;
                }
            }
        }
    } catch (IOException ex) {
        jlGuardarError.setText("Ha ocurrido un error al guardar los datos.");
    }

    return false;
    
    }


    private void crearDirectorio() {
    File directory = new File("data");
    File directory2 = new File("data/usuarios");
    if (!directory.exists()) {
        directory.mkdir();
    }
    if (!directory2.exists()) {
        directory2.mkdir();
    }
    }

    private void crearDirectorioUsuario(String email){
        File directory = new File("data/usuarios/" + email);
        if (!directory.exists()) {
            directory.mkdir();
        }
    }

    //hash para guardar contraseñas (lo hizo chatgpt)
    private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(password.getBytes());
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
        return null;
    }
}


    private void guardarData(String name, String email, String hashPass) {
    crearDirectorio();
    try (FileWriter writer = new FileWriter("data/users.txt", true)) {
        writer.write(name+":"+email + ":" + hashPass + "\n");
    } catch (IOException ex) {
        jlGuardarError.setText("Ha ocurrido un error al guardar los datos.");
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlCorreoError;
    private javax.swing.JLabel jlGuardarError;
    private javax.swing.JLabel jlNameError;
    private javax.swing.JLabel jlPassError;
    // End of variables declaration//GEN-END:variables
}
